export const foodModels = {
  b1: { name: 'L.C Special Burger', type: 'burger', color: '#D2691E' },
  b2: { name: 'Fried Chicken Burger', type: 'burger', color: '#CD853F' },
  b3: { name: 'Half Half Burger', type: 'burger', color: '#D2691E' },
  b4: { name: 'Veggie Burger', type: 'burger', color: '#8B7355' },
  b5: { name: 'Double Beef Burger', type: 'burger', color: '#A0522D' },
  b6: { name: 'Double Chicken Burger', type: 'burger', color: '#DEB887' },
  p1: { name: 'L.C Special Pizza', type: 'pizza', color: '#FF6347' },
  p2: { name: 'BBQ Chicken Pizza', type: 'pizza', color: '#FF4500' },
  p3: { name: 'Steak Pizza', type: 'pizza', color: '#B22222' },
  p4: { name: 'Margarita Pizza', type: 'pizza', color: '#DC143C' },
  p5: { name: 'Hawaiian Pizza', type: 'pizza', color: '#FF7F50' },
  p6: { name: 'Veggie Pizza', type: 'pizza', color: '#FF6347' },
  br1: { name: 'Omelette Sandwich', type: 'sandwich', color: '#FFD700' },
  br2: { name: 'Tuna Sandwich', type: 'sandwich', color: '#A0522D' },
  br3: { name: 'French Toast', type: 'sandwich', color: '#DAA520' },
  d1: { name: 'Chocolate Pizza', type: 'dessert', color: '#8B4513' },
  d2: { name: 'Waffle / Pancake', type: 'dessert', color: '#DAA520' },
  d3: { name: 'Ice Cream', type: 'dessert', color: '#F5DEB3' },
  d4: { name: 'Nutella Ice Cream Sandwich', type: 'dessert', color: '#8B6914' },
  d5: { name: 'Ice Coffee & Milkshake', type: 'dessert', color: '#8B4513' },
  d6: { name: 'Soft Drinks', type: 'dessert', color: '#FF1493' },
}
